from .recognition_profile import CURRENT_RECOGNITION_PROFILE


OCR_PROBE_EXPECTED_FRAGMENT = CURRENT_RECOGNITION_PROFILE.keywords[0]
OCR_PROBE_TEXT = OCR_PROBE_EXPECTED_FRAGMENT
OCR_PROBE_RELATIVE_PATH = "ocr-probe/ocr-probe.png"
